### ISSUE TITLE
Eunomia Iterator bug

### ISSUE THREAD

**Issue by fd-Joker** [SJTU-IPADS/eunomia#1]
The iterator.Next() fails to detect insertion in leaf node.
in memstore_eunotree.cc:
```
if (node_->seq != seq_) {
......
}
```
The seq in Eunomia only changes when the node is split. It can not indicate insertion that does not cause leaf node split.

**Comment by zhaoguowang** [comment]
If there is no split, we protect the integrity of Insertion with HTM. Please refer to algorithm 2, line 49 in the paper. The proof of the algorithm is also given in section 4.3!

**Comment by zhaoguowang** [comment]
I think this issue should be closed!!!

**Comment by fd-Joker** [comment]
Hi,

I have checked the proof sketch in the paper. It argues the correctness of
the algorithm. I think the proof is absolute.
What I mean is in memstore_eunotree.cc:142, the Next() method of Iterator
should decide whether to search the leaf node again depending on whether
the leaf node is modified. In Eunomia implementation, the seq attribute of
leaf node only reflects changes of leaf node split, while normal insertion
does not change seq. So I think conditions should be added to check leaf
node modification without node split.
Here is my solution:
```
if (node_->seq != seq_ || key_ <= node_->reserved[leaf_index+1].key) {
  ...
}
```

Thank you.

**Comment by zhaoguowang** [comment]
Without splitting, it is not necessary to detect the insertion after the range query. This still can provide the linearizability. In the proof, by specifying the linearization point, we can ensure all operations are linearizable without "use seq for normal insertion (no-split)."

**Comment by zhaoguowang** [comment]
Can anyone help to close this issue? It seems I do not have the permission... @styxyang  @haibochen
